### PR TITLE
Update to Stylelint 16

### PR DESCRIPTION
**Pull request by colinrotherham**
This PR updates the project to use Stylelint 16

The upgrade to Stylelint 16 [removes rules deprecated in Stylelint 15](#breaking-change-removal-of-stylistic-rules) following PR https://github.com/alphagov/stylelint-config-gds/pull/32

### Breaking change: Requires Node.js v18.12.0+

The minimum Node.js version is now v18.12.0 but note the following changes for Stylelint API users:

* Supports ES module plugins, custom syntaxes and formatters
* Updates rules, formatters and utilities to return Promises
* Deprecates the CommonJS Node.js API

Read about other breaking changes in the Stylelint [**Migrating to v16.0.0**](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-16.md#breaking-changes) guide.

### CODE REVIEW

**Comment by hannako** [comment]
:wave: is there a plan to review/merge this PR soon?

**Comment by colinrotherham** [comment]
> 👋 is there a plan to review/merge this PR soon?

Hopefully got a few more people in this week to pick up a code review. Thanks @hannako

**Review by romaricpascal — APPROVED** [review]
Neat! ⛵ 

I'd be keen to follow this PR with one that triggers the release. Do you foresee anything that would delay it?

**Comment by colinrotherham** [comment]
@romaricpascal Cheers. Nah, this PR is all that blocked it so I'll open one now

**Comment by colinrotherham** [comment]
We've released this now @hannako 👍

https://www.npmjs.com/package/stylelint-config-gds

**Pull request merged**
